### ISSUE TITLE
Youtube Video is paused after 2 seconds

### ISSUE THREAD

**Issue by wkuranowski** [kurtextrem/StopAutoplay#4]
Hello.

I have another issue. I am using non-extended version and videos are paused after about 1-2 seconds. Please look at "Turn Of The Lights" extension - they are able to stop video at 00:00.

**Comment by kurtextrem** [comment]
I noticed that too. I planned looking at it in a week (once I'm back from holidays)

**Comment by kurtextrem** [comment]
Just for the future: Youtubes API is unreliable, sometimes my event handler is called after 0.8s, sometimes after 1s etc.

**Comment by kurtextrem** [comment]
This issue is fixed with https://github.com/kurtextrem/StopAutoplay/commit/094a9468190e857ee07308651ca21281715553ec now. As always, I'll do some days testing and then I'll publish.

**Comment by kurtextrem** [comment]
https://codereview.chromium.org/1292433002/
This will replace my Stop Autoplay for Youtube Extended extension. It works in the same way, just native.

**Comment by kurtextrem** [comment]
I've released the update now. It's currently rolling out.
